### ISSUE TITLE
Blender fails to build with openimageio 1.8

### ISSUE THREAD

**Issue by onodera-punpun** [6c37/crux-ports#114]
I'll try fixing this, I can't seem to immediately pinpoint the problem (something with oiio).

```
/usr/src/pkg/wrk/blender/src/blender-2.79/intern/cycles/graph/../graph/node_xml.h:31:51: error: reference to 'pugi' is ambiguous
 void xml_read_node(XMLReader& reader, Node *node, pugi::xml_node xml_node);
                                                   ^~~~
In file included from /usr/src/pkg/wrk/blender/src/blender-2.79/intern/cycles/graph/../util/util_xml.h:22:0,
                 from /usr/src/pkg/wrk/blender/src/blender-2.79/intern/cycles/graph/../graph/node_xml.h:23,
                 from /usr/src/pkg/wrk/blender/src/blender-2.79/intern/cycles/graph/node_xml.cpp:17:
/usr/include/OpenImageIO/pugixml.hpp:109:28: note: candidates are: namespace pugi = OpenImageIO_v1_8::OpenImageIO_v1_8::pugi;
 namespace pugi = OIIO::pugi;
                            ^
/usr/include/OpenImageIO/pugixml.hpp:107:11: note:                 namespace OpenImageIO_v1_8::pugi { }
 namespace pugi {}
           ^~~~
In file included from /usr/src/pkg/wrk/blender/src/blender-2.79/intern/cycles/graph/node_xml.cpp:17:0:
```

**Comment by rtlanceroad** [comment]
Although I am not familiar with C++, not from what I see. it's namespace prblem: So you can change `blender-2.79/intern/cycles/graph/node_xml.h` line 31 like the following: 
```
void xml_read_node(XMLReader& reader, Node *node, OpenImageIO_v1_8::OpenImageIO_v1_8::pugi::xml_node xml_node);
```
or
```
void xml_read_node(XMLReader& reader, Node *node, OIIO::pugi::xml_node xml_node);
```

The above two, like the error says, are candidates to choose. You can choose one of them and try if it works. If it works for you, please generate a patch and push it to our repo.

**Comment by onodera-punpun** [comment]
I wonder what causes this because Google doesn't display any results when I search for the error. Maybe we use a newer OIIO than most distros?

**Comment by rtlanceroad** [comment]
Yeah I guess so.
